"""Typed, provenance-aware evidence fusion primitives."""

from .adapters import (
    EvidenceAdapterError,
    data_dragon_snapshot_from_identity,
    riot_match_from_summary_row,
)

from .fusion import (
    DataDragonSnapshot,
    EvidenceBundle,
    EvidenceBundleDisposition,
    EvidenceClaim,
    EvidenceConfidence,
    EvidenceConflict,
    EvidenceFreshness,
    EvidenceGap,
    EvidenceJoin,
    EvidenceJoinKey,
    EvidenceJoinStatus,
    EvidenceSource,
    OfficialPatchEvidence,
    RiotMatchEvidence,
    fuse_evidence,
)
from .storage import (
    EvidenceBundleSnapshot,
    EvidenceSnapshotFreshness,
    EvidenceSnapshotView,
    EvidenceSnapshotWriteDisposition,
    EvidenceSnapshotWriteResult,
    PendingEvidenceBundleSnapshot,
    ProductRunState,
    ProductRunStateValue,
    ProductStateReason,
    bundle_from_storage_projection,
    bundle_to_storage_projection,
    project_evidence_snapshot,
    project_product_run_state,
)

__all__ = [
    "DataDragonSnapshot",
    "EvidenceAdapterError",
    "EvidenceBundle",
    "EvidenceBundleDisposition",
    "EvidenceBundleSnapshot",
    "EvidenceClaim",
    "EvidenceConfidence",
    "EvidenceConflict",
    "EvidenceFreshness",
    "EvidenceGap",
    "EvidenceJoin",
    "EvidenceJoinKey",
    "EvidenceJoinStatus",
    "EvidenceSource",
    "EvidenceSnapshotFreshness",
    "EvidenceSnapshotView",
    "EvidenceSnapshotWriteDisposition",
    "EvidenceSnapshotWriteResult",
    "PendingEvidenceBundleSnapshot",
    "OfficialPatchEvidence",
    "RiotMatchEvidence",
    "ProductRunState",
    "ProductRunStateValue",
    "ProductStateReason",
    "bundle_from_storage_projection",
    "bundle_to_storage_projection",
    "fuse_evidence",
    "data_dragon_snapshot_from_identity",
    "riot_match_from_summary_row",
    "project_evidence_snapshot",
    "project_product_run_state",
]
