"""Provider-neutral model contracts and implementations."""

from .capabilities import (
    CapabilityNegotiation,
    ProviderCapabilities,
    ProviderCapability,
    negotiate_capabilities,
    require_provider_capabilities,
    required_capabilities_for,
)
from .config import (
    ProviderRegistrySettings,
    ZhipuSettings,
    create_provider_registry,
    create_zhipu_provider,
    load_provider_registry_settings,
    load_zhipu_settings,
)
from .errors import (
    ProviderAuthenticationError,
    ProviderCapabilityError,
    ProviderConfigurationError,
    ProviderError,
    ProviderRateLimitError,
    ProviderRegistryError,
    ProviderResponseError,
    ProviderTimeoutError,
    ProviderUnavailableError,
)
from .models import (
    ChatMessage,
    ChatRequest,
    ChatResponse,
    MessageRole,
    StructuredResponseContract,
    TokenUsage,
    ToolCall,
    ToolChoiceMode,
    ToolSpec,
)
from .protocol import LLMProvider
from .registry import (
    ProviderDescriptor,
    ProviderRegistry,
    ProviderSelection,
)
from .zhipu import ZhipuProvider
from .zhipu_profiles import (
    ZHIPU_GLM52_MODEL,
    ZHIPU_GLM52_THINKING_PROFILE,
    ZHIPU_GLM53_FLASH_MODEL,
    ZHIPU_GLM53_FLASH_THINKING_PROFILE,
    ZHIPU_GLM53_MODEL,
    ZHIPU_GLM53_THINKING_PROFILE,
    ZHIPU_LEGACY_THINKING_PROFILE,
    ZHIPU_STANDARD_BASE_URL,
    ZhipuModelProfile,
    ZhipuThinkingProfile,
    get_zhipu_model_profile,
    resolve_zhipu_profile,
    resolve_zhipu_thinking_profile,
    validate_zhipu_profile_for_model,
)
from .structured import (
    StructuredDecodeResult,
    StructuredRepairRequest,
    contract_for_model,
    decode_structured_response,
)
from .secrets import (
    InMemorySecretSource,
    SecretConfigurationError,
    SecretMaterial,
    SecretSource,
)

__all__ = [
    "ChatMessage",
    "ChatRequest",
    "ChatResponse",
    "CapabilityNegotiation",
    "LLMProvider",
    "MessageRole",
    "ProviderAuthenticationError",
    "ProviderCapabilities",
    "ProviderCapability",
    "ProviderCapabilityError",
    "ProviderConfigurationError",
    "ProviderError",
    "ProviderRateLimitError",
    "ProviderDescriptor",
    "ProviderRegistry",
    "ProviderRegistryError",
    "ProviderRegistrySettings",
    "ProviderResponseError",
    "ProviderTimeoutError",
    "ProviderUnavailableError",
    "ProviderSelection",
    "StructuredResponseContract",
    "StructuredDecodeResult",
    "StructuredRepairRequest",
    "TokenUsage",
    "ToolCall",
    "ToolChoiceMode",
    "ToolSpec",
    "ZhipuProvider",
    "ZhipuModelProfile",
    "ZhipuSettings",
    "ZhipuThinkingProfile",
    "ZHIPU_GLM52_MODEL",
    "ZHIPU_GLM52_THINKING_PROFILE",
    "ZHIPU_GLM53_FLASH_MODEL",
    "ZHIPU_GLM53_FLASH_THINKING_PROFILE",
    "ZHIPU_GLM53_MODEL",
    "ZHIPU_GLM53_THINKING_PROFILE",
    "ZHIPU_LEGACY_THINKING_PROFILE",
    "ZHIPU_STANDARD_BASE_URL",
    "InMemorySecretSource",
    "SecretConfigurationError",
    "SecretMaterial",
    "SecretSource",
    "create_provider_registry",
    "create_zhipu_provider",
    "contract_for_model",
    "decode_structured_response",
    "load_provider_registry_settings",
    "load_zhipu_settings",
    "get_zhipu_model_profile",
    "resolve_zhipu_profile",
    "resolve_zhipu_thinking_profile",
    "validate_zhipu_profile_for_model",
    "negotiate_capabilities",
    "require_provider_capabilities",
    "required_capabilities_for",
]
